
# Test Configuration for VGS Application
server:
  port: 5000
  address: 0.0.0.0

spring:
  profiles:
    active: test
  application:
    name: vgs-embedded-test

# Test-optimized settings
couchbase:
  connection-string: ${COUCHBASE_CONNECTION_STRING}
  username: ${COUCHBASE_USERNAME}
  password: ${COUCHBASE_PASSWORD}
  bucket-name: ${COUCHBASE_BUCKET_NAME:vgs-test}
  pool:
    min-endpoints: 2
    max-endpoints: 4
  timeout:
    connect: 10s
    kv: 5s

management:
  server:
    port: 5001
    address: 0.0.0.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
      base-path: /actuator

logging:
  level:
    root: DEBUG
    com.vgs: TRACE
