server:
  port: 5100
  address: 0.0.0.0
  tomcat:
    threads:
      max: 200        # Optimized for 4 vCPUs
      min-spare: 50   # Keep threads ready
    max-connections: 8192
    accept-count: 100
    connection-timeout: 20000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: vgs-embedded-document
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=10000,expireAfterWrite=5m
  task:
    execution:
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 100
    scheduling:
      pool:
        size: 4         # 1x vCPUs
  couchbase:
    connection-string: couchbases://cb.your-cluster.cloud.couchbase.com
    username: ${COUCHBASE_USERNAME:admin}
    password: ${COUCHBASE_PASSWORD:password}
    bucket-name: ${COUCHBASE_BUCKET_NAME:vgs-gaming}
    # Optimized connection pooling
    io:
      min-endpoints: 2
      max-endpoints: 8
      idle-http-connection-timeout: 30s
    timeout:
      connect: 10s
      key-value: 2500ms
      query: 30s
    compression:
      enabled: true
      min-ratio: 0.83

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,caches
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        http.server.requests: true
        vgs.cache.get.latency: true
        vgs.cache.put.latency: true
        vgs.couchbase.connection.latency: true
      percentiles:
        http.server.requests: 0.5, 0.9, 0.95, 0.99
        vgs.cache.get.latency: 0.5, 0.9, 0.95, 0.99
        vgs.cache.put.latency: 0.5, 0.9, 0.95, 0.99
        vgs.couchbase.connection.latency: 0.5, 0.9, 0.95, 0.99

# Logging - Optimized for t3.xlarge performance
logging:
  level:
    com.vgs.kvpoc.embedded: INFO    # Reduced from DEBUG for performance
    com.couchbase: WARN             # Reduced from INFO for performance
    org.springframework.web: WARN   # Reduced from INFO for performance
    org.springframework.boot: WARN
    org.apache.tomcat: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{20} - %msg%n"  # Shorter logger names
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{20} - %msg%n"
  file:
    name: target/spring.log
    max-size: 50MB                  # Smaller files for better I/O
    max-history: 3                  # Fewer files to reduce disk usage
  logback:
    rollingpolicy:
      max-file-size: 50MB
      total-size-cap: 200MB