
# AWS Production Configuration
server:
  port: 5100
  address: 0.0.0.0

spring:
  profiles:
    active: prod
  application:
    name: vgs-embedded-production

# Optimized for AWS environment
couchbase:
  connection-string: ${COUCHBASE_CONNECTION_STRING}
  username: ${COUCHBASE_USERNAME}
  password: ${COUCHBASE_PASSWORD}
  bucket-name: ${COUCHBASE_BUCKET_NAME}
  pool:
    min-endpoints: 8
    max-endpoints: 16
  timeout:
    connect: 10s
    kv: 3s
    query: 30s

# Threading and async configuration
async:
  pool:
    core-size: 10
    max-size: 50
    queue-capacity: 100
    thread-name-prefix: "vgs-async-"

# Circuit breaker configuration
circuit-breaker:
  failure-rate-threshold: 50
  wait-duration-in-open-state: 30s
  sliding-window-size: 100
  minimum-number-of-calls: 10

# Cache configuration
cache:
  type: caffeine
  caffeine:
    spec: maximumSize=10000,expireAfterAccess=5m

management:
  server:
    port: 5101
    address: 0.0.0.0
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.vgs: DEBUG
    com.couchbase: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /var/log/vgs-application.log
