# Test Configuration for Benchmark Testing (No Couchbase)
server:
  port: 5300
  address: 0.0.0.0

spring:
  application:
    name: vgs-transaction-index-test
  main:
    allow-bean-definition-overriding: true
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.couchbase.CouchbaseAutoConfiguration

# Disable Couchbase for testing
couchbase:
  enabled: false

# Use in-memory cache only
cache:
  type: caffeine
  caffeine:
    spec: maximumSize=10000,expireAfterAccess=5m

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always

# Logging for testing
logging:
  level:
    com.vgs: INFO
    org.springframework: WARN
    root: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{20} - %msg%n"

